### ISSUE TITLE
关于Easy Mock API问题

### ISSUE THREAD

**Issue by MoonCheung** [gxt19940130/demos#3]
今天遇到根据您的Mock API链接地址里面出现404,因此没办法借用您的源码练习。请问您能不能把知乎API再次开通一下呢

**Comment by gxt19940130** [comment]
是开通的呀

**Comment by MoonCheung** [comment]
在您的Demo源码里面api.config.js出现404 Not Found呢
![qq 20180410121154](https://user-images.githubusercontent.com/19801190/38535912-c848f3a8-3cb8-11e8-9a31-2797694b3216.png)

**Comment by gxt19940130** [comment]
这个地方没有返回数据，只返回了一个空列表，为了样式展示
你需要选择post请求或者直接在链接后加上method = post；
完整链接
https://www.easy-mock.com/mock/5a39d3d2717d4953ed48bd47/weChatApp/zhixiaohu/home/focusList#!method=POST
![image](https://user-images.githubusercontent.com/17588631/38541818-cb8c865a-3cd2-11e8-9f0e-6861f3d25ef6.png)

**Comment by MoonCheung** [comment]
感谢您无私贡献Demo，我差不多完成半成品Demo,接下来学习easy-Mock中文网数据接口，不过wafar Node后台不好弄。怪不得调用Mock API数据接口呢
